name: .NET CI

on:
  push:
    branches: ["development", "feature/*", "main"]  # Run tests on all branches
  pull_request:
    branches: ["main", "development"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      - name: Restore dependencies (RedoxMod)
        run: dotnet restore RedoxMod/RedoxMod.sln

      - name: Build (RedoxMod)
        run: dotnet build RedoxMod/RedoxMod.sln --no-restore --configuration Release

      # Run tests for RedoxMod.Tests
      - name: Restore dependencies (RedoxMod.Tests)
        run: dotnet restore RedoxMod.Tests/RedoxMod.Tests.csproj

      - name: Build (RedoxMod.Tests)
        run: dotnet build RedoxMod.Tests/RedoxMod.Tests.csproj --no-restore --configuration Release

      - name: Run tests (RedoxMod.Tests)
        run: dotnet test RedoxMod.Tests/RedoxMod.Tests.csproj --no-build --configuration Release --verbosity normal
